SET SCHEMA FN72094;

CREATE TABLE Tech(
    cameraModel CHAR(15) NOT NULL CONSTRAINT PK_TECH_CAMERAMODEL PRIMARY KEY ,
    cameraProducer VARCHAR(20)
);

CREATE TABLE Users(
    userNumber CHAR(8) NOT NULL CONSTRAINT PK_USERS_USERNUMBER PRIMARY KEY ,
    userName CHAR (10) NOT NULL CONSTRAINT UQ_USERS_USERNAME UNIQUE ,
    password VARCHAR(30),
    dateOfFirstAccess DATE DEFAULT CURRENT_DATE ,
    numberOfSubscribers INT
);

CREATE TABLE Videos(
  videoNumber CHAR(8) NOT NULL CONSTRAINT PK_VIDEOS_VIDEONUMBER PRIMARY KEY ,
  title VARCHAR(50) NOT NULL ,
  author VARCHAR(30),
  lengthInSec INT NOT NULL,
  dateOfPublish DATE DEFAULT CURRENT_DATE ,
  numberOfViews INT,
  cameraModel CHAR(15) REFERENCES TECH(cameraModel),
  userNumber CHAR(8) REFERENCES USERS(userNumber)
);

CREATE TABLE Category(
    categoryName CHAR(30) NOT NULL CONSTRAINT PK_CATEGORY_CATEGORYNAME PRIMARY KEY
);

CREATE TABLE hasCategory(
    videoNumber CHAR(8) NOT NULL REFERENCES VIDEOS(VIDEONUMBER),
    categoryName CHAR(30) NOT NULL REFERENCES CATEGORY(CATEGORYNAME),
    CONSTRAINT PK_HASCATEGORY PRIMARY KEY (videoNumber, categoryName)
);

CREATE TABLE subscribeFor(
    userNumber1 CHAR(8) NOT NULL REFERENCES USERS(userNumber),
    userNumber2 CHAR(8) NOT NULL REFERENCES USERS(userNumber),
    CONSTRAINT CK_SUBSCRIBEFOR CHECK ( userNumber1 != userNumber2 ),
    CONSTRAINT PK_SUBSCRIBEFOR PRIMARY KEY (userNumber1, userNumber2)
);